version: "3.7"


networks:
    default:
      ipam:
        config:
            - subnet: 172.18.0.0/24


services:
    client:
        container_name: client
        image: environment:client
        build:
            context: ./client
            dockerfile: Dockerfile
        env_file:
            - ./.envs/client.env
            - ./.envs/db_uri.env
        volumes: 
            - ./client/Workspace:/root/Workspace
            - ./client/jupyter:/root/.jupyter
            - ./client/pyenv-cache:/root/.pyenv/cache
        depends_on:
            - mysql
            - mongo
        links: 
            - mysql
            - mongo
        ports: 
            - 8888:8888
        networks:
            default:
                ipv4_address: 172.18.0.2

    mysql:
        container_name: mysql
        image: environment:mysql
        build: 
            context: ./mysql
            dockerfile: Dockerfile
        env_file: 
            - ./.envs/mysql.env
        command: 
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes: 
            - ./mysql/data:/var/lib/mysql
        ports: 
            - 3306:3306
        networks:
            default:
                ipv4_address: 172.18.0.3

    mongo:
        container_name: mongo
        image: environment:mongo
        build:
            context: ./mongo
            dockerfile: Dockerfile
        env_file: 
            - ./.envs/mongo.env
        volumes: 
            - ./mongo/data:/data/db
        ports: 
            - 27017:27017
        networks:
            default:
                ipv4_address: 172.18.0.4